{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: inventory-client
    tier: frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: inventory-client
  template:
    metadata:
      labels:
        app: inventory-client
        tier: frontend
    spec:
      containers:
      - name: inventory-client
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "{{ .Values.frontend.env.REACT_APP_API_URL }}"
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
{{- end }}
