apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.backend.serviceMonitor.name }}
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: inventory-server
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
